name: JMeter Performance Test

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check JMeter
        run: jmeter --version

      - name: Run JMeter Test
        run: jmeter -n -t blazetest.jmx -l results.jtl