name: JMeter Performance Test

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download JMeter
        run: |
          curl -L -o jmeter.zip https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip
          powershell Expand-Archive jmeter.zip -DestinationPath .

      - name: Run JMeter Test
        run: |
          .\apache-jmeter-5.6.3\bin\jmeter.bat -n -t blazetest.jmx -l results.jtl

      - name: Generate HTML Report
        run: |
          .\apache-jmeter-5.6.3\bin\jmeter.bat -g results.jtl -o report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: JMeter-Report
          path: report